### ISSUE TITLE
GUI Issue: NIC definition to EPA configuration

### ISSUE THREAD

**Issue by jambig** [vanlittle/VNF-Onboarding#29]
When going from NIC definition (screen 2) to EPA configuration, the overview (on the left side) shows that you are in step 3, but you do not get options for EPA configuration.
See added screenshot for example.
<img width="1175" alt="screen shot 2018-02-27 at 16 21 09" src="https://user-images.githubusercontent.com/36893051/36906446-3994ad32-1e36-11e8-8e4d-825a5708d58b.png">

**Comment by nandkumarj** [comment]
This problem is specific to Riftio.

**Comment by nandkumarj** [comment]
In current implementation Riftio does not support EPA parameters. Riftio blueprint should have placeholders for Guest EPA parameters. This is being followed up with Riftio.  From UI side  changes would be needed so that EPA parameters page appear in blueprint generation flow and those inputs could be captured.

**Comment by vanlittle** [comment]
This issue was moved to vmware/bellhop#25
